version: "2"
services:
  cqpweb:
   image: rahonabe/cqpweb
   env_file: ./secrets.env
   domainname: ${DOMAINNAME}
   hostname: ${FIRSTNAME}-CQPweb
   build: 
      context: ./CQPweb
   ports:
       - 8080:80
   volumes:
       - ${CORPORA}:/var/corpora
       - ${REGISTRY}:/usr/local/share/cwb/registry
       - ./${FIRSTNAME}-container/cqpweb/upload:/var/cqpweb/upload
       - ./${FIRSTNAME}-container/cqpweb/data:/var/www/html
       - ./${FIRSTNAME}-container/cqpweb/tmp:/var/cqpweb/tmp
   platform: linux/amd64
  sql:
    image: mariadb
    env_file: ./secrets.env
    domainname: ${DOMAINNAME}
    hostname: ${FIRSTNAME}-sql
    volumes:
      - ./${FIRSTNAME}-container/sql/data:/var/lib/mysql
    volumes_from:
        - cqpweb
